{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2024 Embarcadero Technologies, Inc. }
{              All rights reserved                      }
{                                                       }
{*******************************************************}

const UnicodeDataVersion = '15.0.0';
const UnicodeLastChar = 1114111;
{$DEFINE INDEXTABLE_IS_BYTE}
