{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{                                                       }
{ Copyright(c) 1995-2024 Embarcadero Technologies, Inc. }
{              All rights reserved                      }
{                                                       }
{*******************************************************}

type
  wctrans_t = Integer;
  {$EXTERNALSYM wctrans_t}
  Pwctrans_t = ^wctrans_t;
